import DS from 'ember-data';

export default DS.Model.extend({
    "teamId": DS.attr(),
    "firstnames": DS.attr(),
    "surname": DS.attr(),
    "age": DS.attr(),
    "wage": DS.attr(),
    "rating": DS.attr(),
    "endurance": DS.attr(),
    "technique": DS.attr(),
    "bowling": DS.attr(),
    "batting": DS.attr(),
    "power": DS.attr(),
    "keeping": DS.attr(),
    "fielding": DS.attr(),
    "experience": DS.attr(),
    "captaincy": DS.attr(),
    "form": DS.attr(),
    "fatigue": DS.attr(),
    "batRight": DS.attr(),
    "bowlRight": DS.attr(),
    "bowlerType": DS.attr(),
    "shirtNumber": DS.attr(),
    "training": DS.attr(),
    "youth": DS.attr(),
    "nationality": DS.attr(),
    "youthPromotionDate": DS.attr(),
    "youthPromotionTeam": DS.attr(),
    "talent1": DS.attr(),
    "talent2": DS.attr(),
    "date": DS.attr(),
    "playerId": DS.attr()
});
